### ISSUE TITLE
Great library

### ISSUE THREAD

**Issue by slothbag** [TrekDev/net-ipfs-api#1]
Just wanted to say thanks for this library.  Just tried adding a file to IPFS, works great.

How complete would you say it is? is it like 90% of the IPFS API working?  Do you plan on adding any new features?

I'm going to ask the IPFS guys to link to this repo for a C# implementation if you don't mind,.

**Comment by TrekDev** [comment]
Hi @slothbag. Thanks very much.

I think it's almost there. I've just checked the [command reference](https://ipfs.io/docs/commands/) and some new commands have popped up since I last checked, so I might look into adding those before merging into master & tagging. It'll probably need some clean-up before I'm 100% happy with it, then I'll look into publishing a nuget package to make it super easy to use.

I'll do some more testing as soon as I have time. If you find anything that doesn't work as expected then I'll get onto it asap.

-TD

**Comment by slothbag** [comment]
The tuple<string, stream> syntax was confusing at first.. I had to dig through source code to realize the string was for the filename :)

nuget would be awesome.. my latest C#/JS project I have been packaging everything using the IPFS based GX package manager.. i'll add this too :)

**Comment by slothbag** [comment]
Ha, can you believe it, my project requires a IPFS API library and an Ethereum API library.. I just saw your other repo :)

I have been using https://github.com/Nethereum/Nethereum but its still very much alpha right now.  How stable is your lib?

**Comment by jeremyellis** [comment]
Ah, yeah, sorry about that tuple syntax. That's the first thing on my list to change :)

I'm using both the Ipfs/ethereum clients I wrote for a work project right now, and haven't had many problems recently. I obviously fix any if/when we come across them, but because we mostly use the same functions a lot of the time there are some features which aren't as tested as I'd like them to be.

**Comment by TrekDev** [comment]
Ha that's lucky then. Sorry about that tuple syntax. That's the first thing on my list of changes :)

As for stability: I'm using both ipfs/ethereum clients for a work project, so they'll be supported & improved upon for a long time (at least a couple of years). Any problems we come across obviously get fixed asap, but because we use the same function a lot there are some things that aren't as tested as I'd like.

Nethereum looks good, a bit complex/bulky for my liking though.

**Comment by TrekDev** [comment]
@slothbag Tuples are now `NamedStreams` for `IpfsClient.Add(...)` :)
